// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.27.0--rc1
// source: game.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgId int32

const (
	MsgId_MID_NULL              MsgId = 0
	MsgId_MID_REQ_CONNECT_PLUSE MsgId = 10001 //心跳
	MsgId_MID_RSP_CONNECT_PLUSE MsgId = 20001 //心跳
	MsgId_MID_REQ_JOIN          MsgId = 11001 //加入
	MsgId_MID_RSP_JOIN          MsgId = 21001 //加入
	MsgId_MID_REQ_QUIT          MsgId = 11002 //退出
	MsgId_MID_RSP_QUIT          MsgId = 21002 //退出
	MsgId_MID_REQ_OPERATE       MsgId = 11003 //操作
	MsgId_MID_RSP_OPERATE       MsgId = 21003 //操作
	MsgId_MID_NTF_JOIN          MsgId = 50001 //加入房间
	MsgId_MID_NTF_QUIT          MsgId = 50002 //退出房间
	MsgId_MID_NTF_GAME_START    MsgId = 50003 //游戏开始
	MsgId_MID_NTF_GAME_END      MsgId = 50004 //游戏结束
	MsgId_MID_NTF_OPERATE       MsgId = 51005 //操作
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:     "MID_NULL",
		10001: "MID_REQ_CONNECT_PLUSE",
		20001: "MID_RSP_CONNECT_PLUSE",
		11001: "MID_REQ_JOIN",
		21001: "MID_RSP_JOIN",
		11002: "MID_REQ_QUIT",
		21002: "MID_RSP_QUIT",
		11003: "MID_REQ_OPERATE",
		21003: "MID_RSP_OPERATE",
		50001: "MID_NTF_JOIN",
		50002: "MID_NTF_QUIT",
		50003: "MID_NTF_GAME_START",
		50004: "MID_NTF_GAME_END",
		51005: "MID_NTF_OPERATE",
	}
	MsgId_value = map[string]int32{
		"MID_NULL":              0,
		"MID_REQ_CONNECT_PLUSE": 10001,
		"MID_RSP_CONNECT_PLUSE": 20001,
		"MID_REQ_JOIN":          11001,
		"MID_RSP_JOIN":          21001,
		"MID_REQ_QUIT":          11002,
		"MID_RSP_QUIT":          21002,
		"MID_REQ_OPERATE":       11003,
		"MID_RSP_OPERATE":       21003,
		"MID_NTF_JOIN":          50001,
		"MID_NTF_QUIT":          50002,
		"MID_NTF_GAME_START":    50003,
		"MID_NTF_GAME_END":      50004,
		"MID_NTF_OPERATE":       51005,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type StatusCode int32

const (
	StatusCode_SC_SUCCESS        StatusCode = 0
	StatusCode_SC_FAILED         StatusCode = 1
	StatusCode_SC_PARAM_ERROR    StatusCode = 2
	StatusCode_SC_CONFIG_ERROR   StatusCode = 3
	StatusCode_SC_ALEADY_IN_ROOM StatusCode = 1000
	StatusCode_SC_ROOM_FULL      StatusCode = 1001 //房间已满
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:    "SC_SUCCESS",
		1:    "SC_FAILED",
		2:    "SC_PARAM_ERROR",
		3:    "SC_CONFIG_ERROR",
		1000: "SC_ALEADY_IN_ROOM",
		1001: "SC_ROOM_FULL",
	}
	StatusCode_value = map[string]int32{
		"SC_SUCCESS":        0,
		"SC_FAILED":         1,
		"SC_PARAM_ERROR":    2,
		"SC_CONFIG_ERROR":   3,
		"SC_ALEADY_IN_ROOM": 1000,
		"SC_ROOM_FULL":      1001,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

type OperateDir int32

const (
	OperateDir_OD_NULL  OperateDir = 0
	OperateDir_OD_UP    OperateDir = 1
	OperateDir_OD_DOWN  OperateDir = 2
	OperateDir_OD_LEFT  OperateDir = 3
	OperateDir_OD_RIGHT OperateDir = 4
)

// Enum value maps for OperateDir.
var (
	OperateDir_name = map[int32]string{
		0: "OD_NULL",
		1: "OD_UP",
		2: "OD_DOWN",
		3: "OD_LEFT",
		4: "OD_RIGHT",
	}
	OperateDir_value = map[string]int32{
		"OD_NULL":  0,
		"OD_UP":    1,
		"OD_DOWN":  2,
		"OD_LEFT":  3,
		"OD_RIGHT": 4,
	}
)

func (x OperateDir) Enum() *OperateDir {
	p := new(OperateDir)
	*p = x
	return p
}

func (x OperateDir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperateDir) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[2].Descriptor()
}

func (OperateDir) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[2]
}

func (x OperateDir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperateDir.Descriptor instead.
func (OperateDir) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64        `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerNo uint32        `protobuf:"varint,2,opt,name=playerNo,proto3" json:"playerNo,omitempty"`
	Pos      *PositionInfo `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`     //当前坐标
	Color    *ColorInfo    `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"` //颜色信息
	MoveDir  OperateDir    `protobuf:"varint,5,opt,name=moveDir,proto3,enum=msg.OperateDir" json:"moveDir,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInfo) GetPlayerNo() uint32 {
	if x != nil {
		return x.PlayerNo
	}
	return 0
}

func (x *PlayerInfo) GetPos() *PositionInfo {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlayerInfo) GetColor() *ColorInfo {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *PlayerInfo) GetMoveDir() OperateDir {
	if x != nil {
		return x.MoveDir
	}
	return OperateDir_OD_NULL
}

type CommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommonReq) Reset() {
	*x = CommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReq) ProtoMessage() {}

func (x *CommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReq.ProtoReflect.Descriptor instead.
func (*CommonReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

type CommonRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommonRsp) Reset() {
	*x = CommonRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRsp) ProtoMessage() {}

func (x *CommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRsp.ProtoReflect.Descriptor instead.
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

type JoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

type JoinRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameCfg    *GameConfig   `protobuf:"bytes,1,opt,name=gameCfg,proto3" json:"gameCfg,omitempty"`
	RoomId     uint64        `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MyPlayerId uint64        `protobuf:"varint,3,opt,name=myPlayerId,proto3" json:"myPlayerId,omitempty"`
	Players    []*PlayerInfo `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *JoinRsp) Reset() {
	*x = JoinRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRsp) ProtoMessage() {}

func (x *JoinRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRsp.ProtoReflect.Descriptor instead.
func (*JoinRsp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRsp) GetGameCfg() *GameConfig {
	if x != nil {
		return x.GameCfg
	}
	return nil
}

func (x *JoinRsp) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *JoinRsp) GetMyPlayerId() uint64 {
	if x != nil {
		return x.MyPlayerId
	}
	return 0
}

func (x *JoinRsp) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

type JoinNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *JoinNtf) Reset() {
	*x = JoinNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNtf) ProtoMessage() {}

func (x *JoinNtf) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNtf.ProtoReflect.Descriptor instead.
func (*JoinNtf) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *JoinNtf) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

type QuitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitReq) Reset() {
	*x = QuitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitReq) ProtoMessage() {}

func (x *QuitReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitReq.ProtoReflect.Descriptor instead.
func (*QuitReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

type QuitRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuitRsp) Reset() {
	*x = QuitRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRsp) ProtoMessage() {}

func (x *QuitRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRsp.ProtoReflect.Descriptor instead.
func (*QuitRsp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

type QuitNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *QuitNtf) Reset() {
	*x = QuitNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitNtf) ProtoMessage() {}

func (x *QuitNtf) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitNtf.ProtoReflect.Descriptor instead.
func (*QuitNtf) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *QuitNtf) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GameStartNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameStartNtf) Reset() {
	*x = GameStartNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStartNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartNtf) ProtoMessage() {}

func (x *GameStartNtf) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartNtf.ProtoReflect.Descriptor instead.
func (*GameStartNtf) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

type GameEndNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameEndNtf) Reset() {
	*x = GameEndNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEndNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEndNtf) ProtoMessage() {}

func (x *GameEndNtf) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEndNtf.ProtoReflect.Descriptor instead.
func (*GameEndNtf) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

type OperateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64     `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Dir      OperateDir `protobuf:"varint,2,opt,name=dir,proto3,enum=msg.OperateDir" json:"dir,omitempty"`
}

func (x *OperateInfo) Reset() {
	*x = OperateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateInfo) ProtoMessage() {}

func (x *OperateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateInfo.ProtoReflect.Descriptor instead.
func (*OperateInfo) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *OperateInfo) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *OperateInfo) GetDir() OperateDir {
	if x != nil {
		return x.Dir
	}
	return OperateDir_OD_NULL
}

type OperateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op *OperateInfo `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
}

func (x *OperateReq) Reset() {
	*x = OperateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateReq) ProtoMessage() {}

func (x *OperateReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateReq.ProtoReflect.Descriptor instead.
func (*OperateReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *OperateReq) GetOp() *OperateInfo {
	if x != nil {
		return x.Op
	}
	return nil
}

type OperateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OperateRsp) Reset() {
	*x = OperateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRsp) ProtoMessage() {}

func (x *OperateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRsp.ProtoReflect.Descriptor instead.
func (*OperateRsp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

type OperateNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameNo uint64         `protobuf:"varint,1,opt,name=frameNo,proto3" json:"frameNo,omitempty"`
	Op      []*OperateInfo `protobuf:"bytes,2,rep,name=op,proto3" json:"op,omitempty"`
}

func (x *OperateNtf) Reset() {
	*x = OperateNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateNtf) ProtoMessage() {}

func (x *OperateNtf) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateNtf.ProtoReflect.Descriptor instead.
func (*OperateNtf) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *OperateNtf) GetFrameNo() uint64 {
	if x != nil {
		return x.FrameNo
	}
	return 0
}

func (x *OperateNtf) GetOp() []*OperateInfo {
	if x != nil {
		return x.Op
	}
	return nil
}

type BodyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId    MsgId  `protobuf:"varint,1,opt,name=msgId,proto3,enum=msg.MsgId" json:"msgId,omitempty"`
	Seq      uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	NeedEcho bool   `protobuf:"varint,3,opt,name=needEcho,proto3" json:"needEcho,omitempty"`
	// Types that are assignable to Body:
	//
	//	*BodyReq_CommonReq
	//	*BodyReq_JoinReq
	//	*BodyReq_QuitReq
	//	*BodyReq_OperateReq
	Body isBodyReq_Body `protobuf_oneof:"Body"`
}

func (x *BodyReq) Reset() {
	*x = BodyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyReq) ProtoMessage() {}

func (x *BodyReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyReq.ProtoReflect.Descriptor instead.
func (*BodyReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15}
}

func (x *BodyReq) GetMsgId() MsgId {
	if x != nil {
		return x.MsgId
	}
	return MsgId_MID_NULL
}

func (x *BodyReq) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *BodyReq) GetNeedEcho() bool {
	if x != nil {
		return x.NeedEcho
	}
	return false
}

func (m *BodyReq) GetBody() isBodyReq_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *BodyReq) GetCommonReq() *CommonReq {
	if x, ok := x.GetBody().(*BodyReq_CommonReq); ok {
		return x.CommonReq
	}
	return nil
}

func (x *BodyReq) GetJoinReq() *JoinReq {
	if x, ok := x.GetBody().(*BodyReq_JoinReq); ok {
		return x.JoinReq
	}
	return nil
}

func (x *BodyReq) GetQuitReq() *QuitReq {
	if x, ok := x.GetBody().(*BodyReq_QuitReq); ok {
		return x.QuitReq
	}
	return nil
}

func (x *BodyReq) GetOperateReq() *OperateReq {
	if x, ok := x.GetBody().(*BodyReq_OperateReq); ok {
		return x.OperateReq
	}
	return nil
}

type isBodyReq_Body interface {
	isBodyReq_Body()
}

type BodyReq_CommonReq struct {
	CommonReq *CommonReq `protobuf:"bytes,10,opt,name=commonReq,proto3,oneof"`
}

type BodyReq_JoinReq struct {
	JoinReq *JoinReq `protobuf:"bytes,11,opt,name=joinReq,proto3,oneof"`
}

type BodyReq_QuitReq struct {
	QuitReq *QuitReq `protobuf:"bytes,12,opt,name=quitReq,proto3,oneof"`
}

type BodyReq_OperateReq struct {
	OperateReq *OperateReq `protobuf:"bytes,13,opt,name=operateReq,proto3,oneof"`
}

func (*BodyReq_CommonReq) isBodyReq_Body() {}

func (*BodyReq_JoinReq) isBodyReq_Body() {}

func (*BodyReq_QuitReq) isBodyReq_Body() {}

func (*BodyReq_OperateReq) isBodyReq_Body() {}

type BodyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId    MsgId      `protobuf:"varint,1,opt,name=msgId,proto3,enum=msg.MsgId" json:"msgId,omitempty"`
	Seq      uint64     `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Status   StatusCode `protobuf:"varint,3,opt,name=status,proto3,enum=msg.StatusCode" json:"status,omitempty"`
	ErrorMsg string     `protobuf:"bytes,4,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	// Types that are assignable to Body:
	//
	//	*BodyRsp_CommonRsp
	//	*BodyRsp_JoinRsp
	//	*BodyRsp_JoinNtf
	//	*BodyRsp_QuitRsp
	//	*BodyRsp_QuitNtf
	//	*BodyRsp_GameStartNtf
	//	*BodyRsp_GameEndNtf
	//	*BodyRsp_OperateRsp
	//	*BodyRsp_OperateNtf
	Body isBodyRsp_Body `protobuf_oneof:"Body"`
}

func (x *BodyRsp) Reset() {
	*x = BodyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyRsp) ProtoMessage() {}

func (x *BodyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyRsp.ProtoReflect.Descriptor instead.
func (*BodyRsp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16}
}

func (x *BodyRsp) GetMsgId() MsgId {
	if x != nil {
		return x.MsgId
	}
	return MsgId_MID_NULL
}

func (x *BodyRsp) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *BodyRsp) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SC_SUCCESS
}

func (x *BodyRsp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (m *BodyRsp) GetBody() isBodyRsp_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *BodyRsp) GetCommonRsp() *CommonRsp {
	if x, ok := x.GetBody().(*BodyRsp_CommonRsp); ok {
		return x.CommonRsp
	}
	return nil
}

func (x *BodyRsp) GetJoinRsp() *JoinRsp {
	if x, ok := x.GetBody().(*BodyRsp_JoinRsp); ok {
		return x.JoinRsp
	}
	return nil
}

func (x *BodyRsp) GetJoinNtf() *JoinNtf {
	if x, ok := x.GetBody().(*BodyRsp_JoinNtf); ok {
		return x.JoinNtf
	}
	return nil
}

func (x *BodyRsp) GetQuitRsp() *QuitRsp {
	if x, ok := x.GetBody().(*BodyRsp_QuitRsp); ok {
		return x.QuitRsp
	}
	return nil
}

func (x *BodyRsp) GetQuitNtf() *QuitNtf {
	if x, ok := x.GetBody().(*BodyRsp_QuitNtf); ok {
		return x.QuitNtf
	}
	return nil
}

func (x *BodyRsp) GetGameStartNtf() *GameStartNtf {
	if x, ok := x.GetBody().(*BodyRsp_GameStartNtf); ok {
		return x.GameStartNtf
	}
	return nil
}

func (x *BodyRsp) GetGameEndNtf() *GameEndNtf {
	if x, ok := x.GetBody().(*BodyRsp_GameEndNtf); ok {
		return x.GameEndNtf
	}
	return nil
}

func (x *BodyRsp) GetOperateRsp() *OperateRsp {
	if x, ok := x.GetBody().(*BodyRsp_OperateRsp); ok {
		return x.OperateRsp
	}
	return nil
}

func (x *BodyRsp) GetOperateNtf() *OperateNtf {
	if x, ok := x.GetBody().(*BodyRsp_OperateNtf); ok {
		return x.OperateNtf
	}
	return nil
}

type isBodyRsp_Body interface {
	isBodyRsp_Body()
}

type BodyRsp_CommonRsp struct {
	CommonRsp *CommonRsp `protobuf:"bytes,10,opt,name=commonRsp,proto3,oneof"`
}

type BodyRsp_JoinRsp struct {
	JoinRsp *JoinRsp `protobuf:"bytes,11,opt,name=joinRsp,proto3,oneof"`
}

type BodyRsp_JoinNtf struct {
	JoinNtf *JoinNtf `protobuf:"bytes,12,opt,name=joinNtf,proto3,oneof"`
}

type BodyRsp_QuitRsp struct {
	QuitRsp *QuitRsp `protobuf:"bytes,13,opt,name=quitRsp,proto3,oneof"`
}

type BodyRsp_QuitNtf struct {
	QuitNtf *QuitNtf `protobuf:"bytes,14,opt,name=quitNtf,proto3,oneof"`
}

type BodyRsp_GameStartNtf struct {
	GameStartNtf *GameStartNtf `protobuf:"bytes,15,opt,name=gameStartNtf,proto3,oneof"`
}

type BodyRsp_GameEndNtf struct {
	GameEndNtf *GameEndNtf `protobuf:"bytes,16,opt,name=gameEndNtf,proto3,oneof"`
}

type BodyRsp_OperateRsp struct {
	OperateRsp *OperateRsp `protobuf:"bytes,17,opt,name=operateRsp,proto3,oneof"`
}

type BodyRsp_OperateNtf struct {
	OperateNtf *OperateNtf `protobuf:"bytes,18,opt,name=operateNtf,proto3,oneof"`
}

func (*BodyRsp_CommonRsp) isBodyRsp_Body() {}

func (*BodyRsp_JoinRsp) isBodyRsp_Body() {}

func (*BodyRsp_JoinNtf) isBodyRsp_Body() {}

func (*BodyRsp_QuitRsp) isBodyRsp_Body() {}

func (*BodyRsp_QuitNtf) isBodyRsp_Body() {}

func (*BodyRsp_GameStartNtf) isBodyRsp_Body() {}

func (*BodyRsp_GameEndNtf) isBodyRsp_Body() {}

func (*BodyRsp_OperateRsp) isBodyRsp_Body() {}

func (*BodyRsp_OperateNtf) isBodyRsp_Body() {}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73,
	0x67, 0x1a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc8, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x2a, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x70,
	0x6f, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x29, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x69,
	0x72, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x73, 0x70, 0x22, 0x09, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x22,
	0x9e, 0x01, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x43, 0x66, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x66, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x79, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x22, 0x32, 0x0a, 0x07, 0x4a, 0x6f, 0x69, 0x6e, 0x4e, 0x74, 0x66, 0x12, 0x27, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x09, 0x0a, 0x07, 0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x71, 0x22,
	0x09, 0x0a, 0x07, 0x51, 0x75, 0x69, 0x74, 0x52, 0x73, 0x70, 0x22, 0x25, 0x0a, 0x07, 0x51, 0x75,
	0x69, 0x74, 0x4e, 0x74, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x74,
	0x66, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x4e, 0x74, 0x66, 0x22,
	0x4c, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x03, 0x64, 0x69,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x2e, 0x0a,
	0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x0c, 0x0a,
	0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x22, 0x48, 0x0a, 0x0a, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x74, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x4e, 0x6f, 0x12, 0x20, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x98, 0x02, 0x0a, 0x07, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x52, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x45, 0x63, 0x68,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6e, 0x65, 0x65, 0x64, 0x45, 0x63, 0x68,
	0x6f, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x28, 0x0a, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x48, 0x00, 0x52, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x07, 0x71,
	0x75, 0x69, 0x74, 0x52, 0x65, 0x71, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x07, 0x71, 0x75,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x42, 0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x22, 0xb4, 0x04, 0x0a, 0x07, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71,
	0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x73, 0x70,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x73, 0x70, 0x48, 0x00, 0x52, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12,
	0x28, 0x0a, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x4e, 0x74, 0x66, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4e, 0x74, 0x66, 0x48, 0x00,
	0x52, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x4e, 0x74, 0x66, 0x12, 0x28, 0x0a, 0x07, 0x71, 0x75, 0x69,
	0x74, 0x52, 0x73, 0x70, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x51, 0x75, 0x69, 0x74, 0x52, 0x73, 0x70, 0x48, 0x00, 0x52, 0x07, 0x71, 0x75, 0x69, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x07, 0x71, 0x75, 0x69, 0x74, 0x4e, 0x74, 0x66, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x4e,
	0x74, 0x66, 0x48, 0x00, 0x52, 0x07, 0x71, 0x75, 0x69, 0x74, 0x4e, 0x74, 0x66, 0x12, 0x37, 0x0a,
	0x0c, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x74, 0x66, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4e, 0x74, 0x66, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4e, 0x74, 0x66, 0x12, 0x31, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x6e,
	0x64, 0x4e, 0x74, 0x66, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x4e, 0x74, 0x66, 0x48, 0x00, 0x52, 0x0a, 0x67,
	0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x4e, 0x74, 0x66, 0x12, 0x31, 0x0a, 0x0a, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x48, 0x00,
	0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x74, 0x66, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x74,
	0x66, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x74, 0x66, 0x42,
	0x06, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x2a, 0xba, 0x02, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x49, 0x44, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12,
	0x1a, 0x0a, 0x15, 0x4d, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x5f, 0x50, 0x4c, 0x55, 0x53, 0x45, 0x10, 0x91, 0x4e, 0x12, 0x1b, 0x0a, 0x15, 0x4d,
	0x49, 0x44, 0x5f, 0x52, 0x53, 0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x5f, 0x50,
	0x4c, 0x55, 0x53, 0x45, 0x10, 0xa1, 0x9c, 0x01, 0x12, 0x11, 0x0a, 0x0c, 0x4d, 0x49, 0x44, 0x5f,
	0x52, 0x45, 0x51, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0xf9, 0x55, 0x12, 0x12, 0x0a, 0x0c, 0x4d,
	0x49, 0x44, 0x5f, 0x52, 0x53, 0x50, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x89, 0xa4, 0x01, 0x12,
	0x11, 0x0a, 0x0c, 0x4d, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x51, 0x55, 0x49, 0x54, 0x10,
	0xfa, 0x55, 0x12, 0x12, 0x0a, 0x0c, 0x4d, 0x49, 0x44, 0x5f, 0x52, 0x53, 0x50, 0x5f, 0x51, 0x55,
	0x49, 0x54, 0x10, 0x8a, 0xa4, 0x01, 0x12, 0x14, 0x0a, 0x0f, 0x4d, 0x49, 0x44, 0x5f, 0x52, 0x45,
	0x51, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x45, 0x10, 0xfb, 0x55, 0x12, 0x15, 0x0a, 0x0f,
	0x4d, 0x49, 0x44, 0x5f, 0x52, 0x53, 0x50, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x45, 0x10,
	0x8b, 0xa4, 0x01, 0x12, 0x12, 0x0a, 0x0c, 0x4d, 0x49, 0x44, 0x5f, 0x4e, 0x54, 0x46, 0x5f, 0x4a,
	0x4f, 0x49, 0x4e, 0x10, 0xd1, 0x86, 0x03, 0x12, 0x12, 0x0a, 0x0c, 0x4d, 0x49, 0x44, 0x5f, 0x4e,
	0x54, 0x46, 0x5f, 0x51, 0x55, 0x49, 0x54, 0x10, 0xd2, 0x86, 0x03, 0x12, 0x18, 0x0a, 0x12, 0x4d,
	0x49, 0x44, 0x5f, 0x4e, 0x54, 0x46, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x10, 0xd3, 0x86, 0x03, 0x12, 0x16, 0x0a, 0x10, 0x4d, 0x49, 0x44, 0x5f, 0x4e, 0x54, 0x46,
	0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0xd4, 0x86, 0x03, 0x12, 0x15, 0x0a,
	0x0f, 0x4d, 0x49, 0x44, 0x5f, 0x4e, 0x54, 0x46, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x45,
	0x10, 0xbd, 0x8e, 0x03, 0x2a, 0x7f, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x43, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x43, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x43, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x47, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x11, 0x53, 0x43,
	0x5f, 0x41, 0x4c, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x49, 0x4e, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10,
	0xe8, 0x07, 0x12, 0x11, 0x0a, 0x0c, 0x53, 0x43, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x46, 0x55,
	0x4c, 0x4c, 0x10, 0xe9, 0x07, 0x2a, 0x4c, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x44, 0x69, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x44, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x4f, 0x44, 0x5f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4f,
	0x44, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x44, 0x5f, 0x4c,
	0x45, 0x46, 0x54, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x44, 0x5f, 0x52, 0x49, 0x47, 0x48,
	0x54, 0x10, 0x04, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_game_proto_goTypes = []interface{}{
	(MsgId)(0),           // 0: msg.MsgId
	(StatusCode)(0),      // 1: msg.StatusCode
	(OperateDir)(0),      // 2: msg.OperateDir
	(*PlayerInfo)(nil),   // 3: msg.PlayerInfo
	(*CommonReq)(nil),    // 4: msg.CommonReq
	(*CommonRsp)(nil),    // 5: msg.CommonRsp
	(*JoinReq)(nil),      // 6: msg.JoinReq
	(*JoinRsp)(nil),      // 7: msg.JoinRsp
	(*JoinNtf)(nil),      // 8: msg.JoinNtf
	(*QuitReq)(nil),      // 9: msg.QuitReq
	(*QuitRsp)(nil),      // 10: msg.QuitRsp
	(*QuitNtf)(nil),      // 11: msg.QuitNtf
	(*GameStartNtf)(nil), // 12: msg.GameStartNtf
	(*GameEndNtf)(nil),   // 13: msg.GameEndNtf
	(*OperateInfo)(nil),  // 14: msg.OperateInfo
	(*OperateReq)(nil),   // 15: msg.OperateReq
	(*OperateRsp)(nil),   // 16: msg.OperateRsp
	(*OperateNtf)(nil),   // 17: msg.OperateNtf
	(*BodyReq)(nil),      // 18: msg.BodyReq
	(*BodyRsp)(nil),      // 19: msg.BodyRsp
	(*PositionInfo)(nil), // 20: gameconfig.PositionInfo
	(*ColorInfo)(nil),    // 21: gameconfig.ColorInfo
	(*GameConfig)(nil),   // 22: gameconfig.GameConfig
}
var file_game_proto_depIdxs = []int32{
	20, // 0: msg.PlayerInfo.pos:type_name -> gameconfig.PositionInfo
	21, // 1: msg.PlayerInfo.color:type_name -> gameconfig.ColorInfo
	2,  // 2: msg.PlayerInfo.moveDir:type_name -> msg.OperateDir
	22, // 3: msg.JoinRsp.gameCfg:type_name -> gameconfig.GameConfig
	3,  // 4: msg.JoinRsp.players:type_name -> msg.PlayerInfo
	3,  // 5: msg.JoinNtf.player:type_name -> msg.PlayerInfo
	2,  // 6: msg.OperateInfo.dir:type_name -> msg.OperateDir
	14, // 7: msg.OperateReq.op:type_name -> msg.OperateInfo
	14, // 8: msg.OperateNtf.op:type_name -> msg.OperateInfo
	0,  // 9: msg.BodyReq.msgId:type_name -> msg.MsgId
	4,  // 10: msg.BodyReq.commonReq:type_name -> msg.CommonReq
	6,  // 11: msg.BodyReq.joinReq:type_name -> msg.JoinReq
	9,  // 12: msg.BodyReq.quitReq:type_name -> msg.QuitReq
	15, // 13: msg.BodyReq.operateReq:type_name -> msg.OperateReq
	0,  // 14: msg.BodyRsp.msgId:type_name -> msg.MsgId
	1,  // 15: msg.BodyRsp.status:type_name -> msg.StatusCode
	5,  // 16: msg.BodyRsp.commonRsp:type_name -> msg.CommonRsp
	7,  // 17: msg.BodyRsp.joinRsp:type_name -> msg.JoinRsp
	8,  // 18: msg.BodyRsp.joinNtf:type_name -> msg.JoinNtf
	10, // 19: msg.BodyRsp.quitRsp:type_name -> msg.QuitRsp
	11, // 20: msg.BodyRsp.quitNtf:type_name -> msg.QuitNtf
	12, // 21: msg.BodyRsp.gameStartNtf:type_name -> msg.GameStartNtf
	13, // 22: msg.BodyRsp.gameEndNtf:type_name -> msg.GameEndNtf
	16, // 23: msg.BodyRsp.operateRsp:type_name -> msg.OperateRsp
	17, // 24: msg.BodyRsp.operateNtf:type_name -> msg.OperateNtf
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_config_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStartNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEndNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_game_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*BodyReq_CommonReq)(nil),
		(*BodyReq_JoinReq)(nil),
		(*BodyReq_QuitReq)(nil),
		(*BodyReq_OperateReq)(nil),
	}
	file_game_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*BodyRsp_CommonRsp)(nil),
		(*BodyRsp_JoinRsp)(nil),
		(*BodyRsp_JoinNtf)(nil),
		(*BodyRsp_QuitRsp)(nil),
		(*BodyRsp_QuitNtf)(nil),
		(*BodyRsp_GameStartNtf)(nil),
		(*BodyRsp_GameEndNtf)(nil),
		(*BodyRsp_OperateRsp)(nil),
		(*BodyRsp_OperateNtf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
